function drawMarkers(){
	//creat all the grids
	//Overworld markers
	var place = document.getElementById("overworld");
	for (i = 0; i < 128; i++){
		markersOW[i] = document.createElement("img");
		markersOW[i].setAttribute("src", "images/marker1.png");
		markersOW[i].setAttribute("class", "owmarker");
		markersOW[i].id = "owmarker" + i;
		markersOW[i].style.left = (( i % 16 ) * 45 ) + 10 + 'px';
		markersOW[i].style.top = ( Math.trunc( i / 16 ) * 31 ) + 10 + 'px';
		markersOW[i].onclick = toggleMarker;
		//markersOW[i].onmouseenter = showTooltip;
		//markersOW[i].onmouseleave = hideTooltip;
		place.appendChild(markersOW[i]);
	}
	
	//Markers for levels 1 - 8
	for (i = 0; i < 96; i++){
		// Lvs one and two
		place = document.getElementById("onetwo");
		markersOneTwo[i] = document.createElement("img");
		markersOneTwo[i].setAttribute("src", "images/marker1.png");
		markersOneTwo[i].setAttribute("class", "lvmarker");
		markersOneTwo[i].id = "otmarker" + i;
		markersOneTwo[i].style.left = (( i % 12 ) * 60 ) + 10 + 'px';
		markersOneTwo[i].style.top = ( Math.trunc( i / 12 ) * 41.2 ) + 10 + 'px';
		markersOneTwo[i].onclick = toggleMarker;
		//markersOneTwo[i].onmouseenter = showTooltip;
		//markersOneTwo[i].onmouseleave = hideTooltip;
		place.appendChild(markersOneTwo[i]);
		
		// Lvs three and four
		place = document.getElementById("threefour");
		markersThreeFour[i] = document.createElement("img");
		markersThreeFour[i].setAttribute("src", "images/marker1.png");
		markersThreeFour[i].setAttribute("class", "lvmarker");
		markersThreeFour[i].id = "tfmarker" + i;
		markersThreeFour[i].style.left = (( i % 12 ) * 60 ) + 10 + 'px';
		markersThreeFour[i].style.top = ( Math.trunc( i / 12 ) * 41.2 ) + 10 + 'px';
		markersThreeFour[i].onclick = toggleMarker;
		//markersThreeFour[i].onmouseenter = showTooltip;
		//markersThreeFour[i].onmouseleave = hideTooltip;
		place.appendChild(markersThreeFour[i]);
		
		// Lvs five and six
		place = document.getElementById("fivesix");
		markersFiveSix[i] = document.createElement("img");
		markersFiveSix[i].setAttribute("src", "images/marker1.png");
		markersFiveSix[i].setAttribute("class", "lvmarker");
		markersFiveSix[i].id = "fsmarker" + i;
		markersFiveSix[i].style.left = (( i % 12 ) * 60 ) + 10 + 'px';
		markersFiveSix[i].style.top = ( Math.trunc( i / 12 ) * 41.2 ) + 10 + 'px';
		markersFiveSix[i].onclick = toggleMarker;
		//markersFiveSix[i].onmouseenter = showTooltip;
		//markersFiveSix[i].onmouseleave = hideTooltip;
		place.appendChild(markersFiveSix[i]);
		
		// Lvs seven and eight
		place = document.getElementById("seveneight");
		markersSevenEight[i] = document.createElement("img");
		markersSevenEight[i].setAttribute("src", "images/marker1.png");
		markersSevenEight[i].setAttribute("class", "lvmarker");
		markersSevenEight[i].id = "semarker" + i;
		markersSevenEight[i].style.left = (( i % 12 ) * 60 ) + 10 + 'px';
		markersSevenEight[i].style.top = ( Math.trunc( i / 12 ) * 41.2 ) + 10 + 'px';
		markersSevenEight[i].onclick = toggleMarker;
		//markersSevenEight[i].onmouseenter = showTooltip;
		//markersSevenEight[i].onmouseleave = hideTooltip;
		place.appendChild(markersSevenEight[i]);
	}
	
	for ( i = 0; i < 64; i++){
		// Lv nine
		place = document.getElementById("nine");
		markersNine[i] = document.createElement("img");
		markersNine[i].setAttribute("src", "images/marker1.png");
		markersNine[i].setAttribute("class", "lvmarker");
		markersNine[i].id = "ninemarker" + i;
		markersNine[i].style.left = (( i % 8 ) * 60 ) + 10 + 'px';
		markersNine[i].style.top = ( Math.trunc( i / 8 ) * 41.2 ) + 10 + 'px';
		markersNine[i].onclick = toggleMarker;
		//markersNine[i].onmouseenter = showTooltip;
		//markersNine[i].onmouseleave = hideTooltip;
		place.appendChild(markersNine[i]);
	}
	
	// customize the grids
	//remove and mark OW spaces without entrances
	makeMarked(markersOW[0]);
	makeMarked(markersOW[2]);
	makeMarked(markersOW[6]);
	makeMarked(markersOW[8]);
	makeMarked(markersOW[9]);
	makeMarked(markersOW[17]);
	makeMarked(markersOW[21]);
	makeMarked(markersOW[23]);
	makeMarked(markersOW[24]);
	makeMarked(markersOW[25]);
	makeMarked(markersOW[27]);
	makeMarked(markersOW[32]);
	makeMarked(markersOW[41]);
	makeMarked(markersOW[42]);
	makeMarked(markersOW[43]);
	makeMarked(markersOW[46]);
	makeMarked(markersOW[48]);
	makeMarked(markersOW[49]);
	makeMarked(markersOW[50]);
	makeMarked(markersOW[53]);
	makeMarked(markersOW[54]);
	makeMarked(markersOW[56]);
	makeMarked(markersOW[58]);
	makeMarked(markersOW[59]);
	makeMarked(markersOW[62]);
	makeMarked(markersOW[63]);
	makeMarked(markersOW[64]);
	makeMarked(markersOW[65]);
	makeMarked(markersOW[76]);
	makeMarked(markersOW[79]);
	makeMarked(markersOW[80]);
	makeMarked(markersOW[82]);
	makeMarked(markersOW[83]);
	makeMarked(markersOW[84]);
	makeMarked(markersOW[85]);
	makeMarked(markersOW[87]);
	makeMarked(markersOW[88]);
	makeMarked(markersOW[89]);
	makeMarked(markersOW[90]);
	makeMarked(markersOW[92]);
	makeMarked(markersOW[93]);
	makeMarked(markersOW[96]);
	makeMarked(markersOW[97]);
	makeMarked(markersOW[101]);
	makeMarked(markersOW[105]);
	makeMarked(markersOW[108]);
	makeMarked(markersOW[110]);
	makeMarked(markersOW[114]);
	makeMarked(markersOW[115]);
	makeMarked(markersOW[122]);
	makeMarked(markersOW[126]);
	makeMarked(markersOW[127]);

	//Levels one and two
	makeBlank(markersOneTwo[0]);
	makeBlank(markersOneTwo[1]);
	makeBlank(markersOneTwo[2]);
	makeBlank(markersOneTwo[3]);
	makeBlank(markersOneTwo[4]);
	makeBlank(markersOneTwo[5]);
	makeBlank(markersOneTwo[6]);
	makeBlank(markersOneTwo[9]);
	makeBlank(markersOneTwo[10]);
	makeBlank(markersOneTwo[11]);
	makeBlank(markersOneTwo[12]);
	makeBlank(markersOneTwo[15]);
	makeBlank(markersOneTwo[16]);
	makeBlank(markersOneTwo[17]);
	makeBlank(markersOneTwo[18]);
	makeBlank(markersOneTwo[19]);
	makeBlank(markersOneTwo[22]);
	makeBlank(markersOneTwo[23]);
	makeBlank(markersOneTwo[24]);
	makeBlank(markersOneTwo[25]);
	makeBlank(markersOneTwo[27]);
	makeBlank(markersOneTwo[30]);
	makeBlank(markersOneTwo[31]);
	makeBlank(markersOneTwo[34]);
	makeBlank(markersOneTwo[35]);
	makeBlank(markersOneTwo[41]);
	makeBlank(markersOneTwo[42]);
	makeBlank(markersOneTwo[43]);
	makeBlank(markersOneTwo[46]);
	makeBlank(markersOneTwo[47]);
	makeBlank(markersOneTwo[48]);
	makeBlank(markersOneTwo[52]);
	makeBlank(markersOneTwo[53]);
	makeBlank(markersOneTwo[54]);
	makeBlank(markersOneTwo[55]);
	makeBlank(markersOneTwo[58]);
	makeBlank(markersOneTwo[59]);
	makeBlank(markersOneTwo[60]);
	makeBlank(markersOneTwo[61]);
	makeBlank(markersOneTwo[63]);
	makeBlank(markersOneTwo[64]);
	makeBlank(markersOneTwo[65]);
	makeBlank(markersOneTwo[66]);
	makeBlank(markersOneTwo[67]);
	makeBlank(markersOneTwo[70]);
	makeBlank(markersOneTwo[71]);
	makeBlank(markersOneTwo[72]);
	makeBlank(markersOneTwo[76]);
	makeBlank(markersOneTwo[77]);
	makeBlank(markersOneTwo[82]);
	makeBlank(markersOneTwo[83]);
	makeBlank(markersOneTwo[84]);
	makeBlank(markersOneTwo[85]);
	makeBlank(markersOneTwo[86]);
	makeBlank(markersOneTwo[87]);
	makeBlank(markersOneTwo[88]);
	makeBlank(markersOneTwo[89]);
	makeBlank(markersOneTwo[90]);
	makeBlank(markersOneTwo[93]);
	makeBlank(markersOneTwo[94]);
	makeBlank(markersOneTwo[95]);

	makeMarked(markersOneTwo[36]);
	makeMarked(markersOneTwo[37]);	
	makeMarked(markersOneTwo[49]);
	makeMarked(markersOneTwo[62]);
	makeMarked(markersOneTwo[74]);
	makeMarked(markersOneTwo[21]);
	makeMarked(markersOneTwo[32]);
	makeMarked(markersOneTwo[68]);
	makeMarked(markersOneTwo[79]);
	makeMarked(markersOneTwo[80]);
	makeMarked(markersOneTwo[91]);
	
	//Levels three and four
	makeBlank(markersThreeFour[0]);
	makeBlank(markersThreeFour[1]);
	makeBlank(markersThreeFour[2]);
	makeBlank(markersThreeFour[3]);
	makeBlank(markersThreeFour[4]);
	makeBlank(markersThreeFour[5]);
	makeBlank(markersThreeFour[10]);
	makeBlank(markersThreeFour[11]);
	makeBlank(markersThreeFour[12]);
	makeBlank(markersThreeFour[15]);
	makeBlank(markersThreeFour[16]);
	makeBlank(markersThreeFour[17]);
	makeBlank(markersThreeFour[22]);
	makeBlank(markersThreeFour[23]);
	makeBlank(markersThreeFour[24]);
	makeBlank(markersThreeFour[25]);
	makeBlank(markersThreeFour[27]);
	makeBlank(markersThreeFour[29]);
	makeBlank(markersThreeFour[32]);
	makeBlank(markersThreeFour[33]);
	makeBlank(markersThreeFour[34]);
	makeBlank(markersThreeFour[35]);
	makeBlank(markersThreeFour[41]);
	makeBlank(markersThreeFour[45]);
	makeBlank(markersThreeFour[46]);
	makeBlank(markersThreeFour[47]);
	makeBlank(markersThreeFour[53]);
	makeBlank(markersThreeFour[55]);
	makeBlank(markersThreeFour[56]);
	makeBlank(markersThreeFour[57]);
	makeBlank(markersThreeFour[58]);
	makeBlank(markersThreeFour[59]);
	makeBlank(markersThreeFour[61]);
	makeBlank(markersThreeFour[63]);
	makeBlank(markersThreeFour[64]);
	makeBlank(markersThreeFour[65]);
	makeBlank(markersThreeFour[68]);
	makeBlank(markersThreeFour[69]);
	makeBlank(markersThreeFour[70]);
	makeBlank(markersThreeFour[71]);
	makeBlank(markersThreeFour[72]);
	makeBlank(markersThreeFour[73]);
	makeBlank(markersThreeFour[76]);
	makeBlank(markersThreeFour[77]);
	makeBlank(markersThreeFour[78]);
	makeBlank(markersThreeFour[81]);
	makeBlank(markersThreeFour[82]);
	makeBlank(markersThreeFour[83]);
	makeBlank(markersThreeFour[84]);
	makeBlank(markersThreeFour[85]);
	makeBlank(markersThreeFour[86]);
	makeBlank(markersThreeFour[87]);
	makeBlank(markersThreeFour[88]);
	makeBlank(markersThreeFour[89]);
	makeBlank(markersThreeFour[92]);
	makeBlank(markersThreeFour[93]);
	makeBlank(markersThreeFour[94]);
	makeBlank(markersThreeFour[95]);
	
	makeMarked(markersThreeFour[14]);
	makeMarked(markersThreeFour[26]);
	makeMarked(markersThreeFour[48]);
	makeMarked(markersThreeFour[51]);
	makeMarked(markersThreeFour[75]);
	makeMarked(markersThreeFour[6]);
	makeMarked(markersThreeFour[8]);
	makeMarked(markersThreeFour[18]);
	makeMarked(markersThreeFour[19]);
	makeMarked(markersThreeFour[20]);
	makeMarked(markersThreeFour[30]);
	makeMarked(markersThreeFour[42]);
	makeMarked(markersThreeFour[43]);
	makeMarked(markersThreeFour[66]);
	makeMarked(markersThreeFour[79]);
	makeMarked(markersThreeFour[91]);
	
	//Levels five and six
	makeBlank(markersFiveSix[0]);
	makeBlank(markersFiveSix[1]);
	makeBlank(markersFiveSix[4]);
	makeBlank(markersFiveSix[5]);
	makeBlank(markersFiveSix[6]);
	makeBlank(markersFiveSix[11]);
	makeBlank(markersFiveSix[12]);
	makeBlank(markersFiveSix[17]);
	makeBlank(markersFiveSix[24]);
	makeBlank(markersFiveSix[29]);
	makeBlank(markersFiveSix[32]);
	makeBlank(markersFiveSix[33]);
	makeBlank(markersFiveSix[36]);
	makeBlank(markersFiveSix[38]);
	makeBlank(markersFiveSix[39]);
	makeBlank(markersFiveSix[41]);
	makeBlank(markersFiveSix[45]);
	makeBlank(markersFiveSix[47]);
	makeBlank(markersFiveSix[48]);
	makeBlank(markersFiveSix[49]);
	makeBlank(markersFiveSix[50]);
	makeBlank(markersFiveSix[53]);
	makeBlank(markersFiveSix[55]);
	makeBlank(markersFiveSix[56]);
	makeBlank(markersFiveSix[57]);
	makeBlank(markersFiveSix[58]);
	makeBlank(markersFiveSix[59]);
	makeBlank(markersFiveSix[60]);
	makeBlank(markersFiveSix[61]);
	makeBlank(markersFiveSix[65]);
	makeBlank(markersFiveSix[67]);
	makeBlank(markersFiveSix[68]);
	makeBlank(markersFiveSix[69]);
	makeBlank(markersFiveSix[70]);
	makeBlank(markersFiveSix[71]);
	makeBlank(markersFiveSix[72]);
	makeBlank(markersFiveSix[77]);
	makeBlank(markersFiveSix[79]);
	makeBlank(markersFiveSix[81]);
	makeBlank(markersFiveSix[82]);
	makeBlank(markersFiveSix[83]);
	makeBlank(markersFiveSix[84]);
	makeBlank(markersFiveSix[85]);
	makeBlank(markersFiveSix[86]);
	makeBlank(markersFiveSix[89]);
	makeBlank(markersFiveSix[93]);
	makeBlank(markersFiveSix[94]);
	makeBlank(markersFiveSix[95]);
	
	makeMarked(markersFiveSix[3]);
	makeMarked(markersFiveSix[14]);
	makeMarked(markersFiveSix[16]);
	makeMarked(markersFiveSix[26]);
	makeMarked(markersFiveSix[37]);
	makeMarked(markersFiveSix[73]);
	makeMarked(markersFiveSix[76]);
	makeMarked(markersFiveSix[87]);
	makeMarked(markersFiveSix[8]);
	makeMarked(markersFiveSix[9]);
	makeMarked(markersFiveSix[18]);
	makeMarked(markersFiveSix[21]);
	makeMarked(markersFiveSix[23]);
	makeMarked(markersFiveSix[34]);
	makeMarked(markersFiveSix[42]);
	makeMarked(markersFiveSix[43]);
	makeMarked(markersFiveSix[44]);
	makeMarked(markersFiveSix[54]);
	makeMarked(markersFiveSix[80]);
	makeMarked(markersFiveSix[90]);
	makeMarked(markersFiveSix[91]);
	
	//levels seven and eight
	makeBlank(markersSevenEight[6]);
	makeBlank(markersSevenEight[7]);
	makeBlank(markersSevenEight[8]);
	makeBlank(markersSevenEight[10]);
	makeBlank(markersSevenEight[11]);
	makeBlank(markersSevenEight[17]);
	makeBlank(markersSevenEight[18]);
	makeBlank(markersSevenEight[19]);
	makeBlank(markersSevenEight[23]);
	makeBlank(markersSevenEight[28]);
	makeBlank(markersSevenEight[29]);
	makeBlank(markersSevenEight[30]);
	makeBlank(markersSevenEight[34]);
	makeBlank(markersSevenEight[35]);
	makeBlank(markersSevenEight[39]);
	makeBlank(markersSevenEight[40]);
	makeBlank(markersSevenEight[41]);
	makeBlank(markersSevenEight[47]);
	makeBlank(markersSevenEight[50]);
	makeBlank(markersSevenEight[51]);
	makeBlank(markersSevenEight[52]);
	makeBlank(markersSevenEight[53]);
	makeBlank(markersSevenEight[58]);
	makeBlank(markersSevenEight[59]);
	makeBlank(markersSevenEight[64]);
	makeBlank(markersSevenEight[65]);
	makeBlank(markersSevenEight[66]);
	makeBlank(markersSevenEight[71]);
	makeBlank(markersSevenEight[78]);
	makeBlank(markersSevenEight[79]);
	makeBlank(markersSevenEight[80]);
	makeBlank(markersSevenEight[82]);
	makeBlank(markersSevenEight[83]);
	makeBlank(markersSevenEight[87]);
	makeBlank(markersSevenEight[88]);
	makeBlank(markersSevenEight[89]);
	makeBlank(markersSevenEight[90]);
	makeBlank(markersSevenEight[95]);
	
	makeMarked(markersSevenEight[0]);
	makeMarked(markersSevenEight[5]);
	makeMarked(markersSevenEight[13]);
	makeMarked(markersSevenEight[14]);
	makeMarked(markersSevenEight[16]);
	makeMarked(markersSevenEight[24]);
	makeMarked(markersSevenEight[25]);
	makeMarked(markersSevenEight[37]);
	makeMarked(markersSevenEight[48]);
	makeMarked(markersSevenEight[49]);
	makeMarked(markersSevenEight[61]);
	makeMarked(markersSevenEight[63]);
	makeMarked(markersSevenEight[74]);
	makeMarked(markersSevenEight[75]);
	makeMarked(markersSevenEight[85]);
	makeMarked(markersSevenEight[21]);
	makeMarked(markersSevenEight[22]);
	makeMarked(markersSevenEight[32]);
	makeMarked(markersSevenEight[42]);
	makeMarked(markersSevenEight[44]);
	makeMarked(markersSevenEight[45]);
	makeMarked(markersSevenEight[56]);
	makeMarked(markersSevenEight[93]);
		
	
	//level nine
	makeBlank(markersNine[0]);
	makeMarked(markersNine[1]);
	makeMarked(markersNine[2]);
	makeMarked(markersNine[3]);
	makeMarked(markersNine[4]);
	makeMarked(markersNine[5]);
	makeMarked(markersNine[6]);
	makeMarked(markersNine[11]);
	makeMarked(markersNine[12]);
	makeMarked(markersNine[15]);
	makeMarked(markersNine[16]);
	makeMarked(markersNine[17]);
	makeMarked(markersNine[18]);
	makeMarked(markersNine[20]);
	makeMarked(markersNine[24]);
	makeMarked(markersNine[25]);
	makeMarked(markersNine[27]);
	makeMarked(markersNine[30]);
	makeMarked(markersNine[33]);
	makeMarked(markersNine[35]);
	makeMarked(markersNine[37]);
	makeMarked(markersNine[38]);
	makeMarked(markersNine[40]);
	makeMarked(markersNine[41]);
	makeMarked(markersNine[42]);
	makeMarked(markersNine[43]);
	makeMarked(markersNine[44]);
	makeMarked(markersNine[45]);
	makeBlank(markersNine[48]);
	makeMarked(markersNine[51]);
	makeMarked(markersNine[52]);
	makeMarked(markersNine[53]);
	makeMarked(markersNine[54]);
	makeBlank(markersNine[55]);
	makeBlank(markersNine[56]);
	makeMarked(markersNine[57]);
	makeBlank(markersNine[58]);
	makeMarked(markersNine[59]);
	makeMarked(markersNine[60]);
	makeBlank(markersNine[61]);
	makeMarked(markersNine[62]);
	makeBlank(markersNine[63]);
}